import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar/index";
import { Providers } from "./DarkModeToggle/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Weatherly",
  description: "Generated by belal,mosab",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
